<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>23a99293-c93d-4838-84e5-42a1f7f0d6fe</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Insuseg.Analytics.Data\Insuseg.Analytics.Data.csproj" />
  </ItemGroup>

</Project>
