// <auto-generated />
using System;
using Insuseg.Analytics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Insuseg.Analytics.Data.Migrations
{
    [DbContext(typeof(InsusegAnalyticsDbContext))]
    [Migration("20260722015656_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Insuseg.Analytics.Data.Entities.Sale", b =>
                {
                    b.Property<int>("DocEntry")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DocNum")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SaleDate")
                        .HasColumnType("date");

                    b.Property<int?>("SalesPersonCode")
                        .HasColumnType("int");

                    b.HasKey("DocEntry");

                    b.HasIndex("SalesPersonCode");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Insuseg.Analytics.Data.Entities.SalesPerson", b =>
                {
                    b.Property<int>("SalesEmployeeCode")
                        .HasColumnType("int");

                    b.Property<string>("SalesEmployeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SalesEmployeeCode");

                    b.ToTable("SalesPersons");
                });

            modelBuilder.Entity("Insuseg.Analytics.Data.Entities.Sale", b =>
                {
                    b.HasOne("Insuseg.Analytics.Data.Entities.SalesPerson", "SalesPerson")
                        .WithMany()
                        .HasForeignKey("SalesPersonCode");

                    b.Navigation("SalesPerson");
                });
#pragma warning restore 612, 618
        }
    }
}
